### ISSUE TITLE
Ettercap set_redir_commands(): cannot setup the redirect for IPv6

### ISSUE THREAD

**Issue by andrea94migliori** [Ettercap/ettercap#1025]
### Ettercap 0.8.3 and Kali Linux 2020

I tried an ARP man-in-the-middle with Ettercap and I got an error:
```
sudo ettercap -Ti eth0 -M arp:remote /192.168.1.1/ /192.168.1.53/

ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team

Incorrect number of token (///) in TARGET !!
```

Then, I read carefully the man page and I thought to solve the problem as follows:
```
sudo ettercap -Ti eth0 -M arp:remote /192.168.1.1// /192.168.1.53//

ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team

Listening on:
  eth0 -> 00:0C:29:25:CA:4E
          192.168.1.145/255.255.255.0
          fe80::20c:29ff:fe25:ca4e/64

set_redir_commands(): cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
```
What is this error due to? I googled it and it seems like everyone else worked it out by simply adding a double / at the end of IP addresses as I did, but in my case it is still not working.

**Comment by koeppea** [comment]
I assume you have uncommended the iptables redir command for IPv4 but not for IPv6. Since Kali has compiled Ettercap with IPv6 support, it requires either iptables redir command for IPv6 uncommented (activated) as well or do comment out (disable) both. Only one doesn't work.

However these redir commands are not required to do pure man-in-the-middle so see the traffic and to do famous stuff like DNS Spoofing. Redir commands are only required for intercepting SSL. But this is related to quite some pitfalls, which for some, there doesn't exists solutions by design.

Feel free to reopen or open a new issue if you have further issues with Ettercap.

**Comment by jrmessiah** [comment]
I came across the same issue...which was solved when i changed the ec_uid = 0 

hope that helps

**Comment by LoneWolf4713** [comment]
Hey , I was having the same issue , and just figured it out by uncommenting the below lines 


#redir6_command_on = "ip6tables -t nat -A PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"
#redir6_command_off = "ip6tables -t nat -D PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"

**Comment by koeppea** [comment]
I think I'll put a comment into the IPv6 version of etter.conf that it is strongly recommended to uncomment the IPv6 related commands and also to care about IPv6 when using ettercap.

**Comment by LoneWolf4713** [comment]
Then you won't be able to do SSL related stuff , i think ? correct me , if I am wrong .

**Comment by koeppea** [comment]
Well this I'm not getting.
The comment is just about making clear that you have to uncomment the redir6 lines as well and that you should consider SSL traffic on IPv6 as well when it's enabled in the network.
