### ISSUE TITLE
The plugin dns_spoof doesn't work

### ISSUE THREAD

**Issue by Tatuck** [Ettercap/ettercap#1026]
Hello! I tried to use the dns_spoof plugin but doesn't work:
etter.dns:
facebook.com   A 192.168.1.50 1030491244 #It shall last forever!
*.facebook.com   A 192.168.1.50 30
etter.conf:
I have the Ipchains with the "#"

But in the victims pc when i search facebook.com it shows this error: ERR_CONNECTION_RESET
And when i search any other page it shows this other error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

What do i have to do???

**Comment by koeppea** [comment]
First please note that the TTL is a 16-bit field in the DNS protocol. When the TTL in _etter.dns_ exceeds the maximum of 65535, Ettercap silently resets it to 3600. However, I don't see much of a reason doing that, since the client DNS cache is flushed anyway when the device is shut down.

To Spoof Facebook is anyway tricky. Many browsers demand proper SSL with no user-recourse (see our[ article to HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS))

I would recommend to start spoofing a non-famous site. Maybe one w/o SSL requirement in the first go.

However, since the victim got redirected to another webserver (the one with SSL issues), DNS spoofing seem to have worked and just the followup part providing the fake website failed.
You should have seem something like 
```
dns_spoof: A [facebook.com] spoofed to [192.168.1.50] TTL [3600 s]
```
Then the DNS Spoofing has worked.

Feel free to reopen if you think otherwise.

**Comment by Tatuck** [comment]
Thanks!
