### ISSUE TITLE
SSLStrip plugin

### ISSUE THREAD

**Issue by saormart** [Ettercap/ettercap#1043]
I'm trying to use the SSLStrip plugin to by-pass the HTTPS/HSTS and seems to kind work on some websites ... but most of them will say "This site can't provide a secure connection"
It works on google for search by returning to the target computer a "unsecured connection"
For mobile devices like iPhone, for some reason it blocks completely the internet traffic on the device... you can't browse or open any app that uses internet !
I'm also using the  dns_spoof plugin to try to redirect the traffic!
I'm wonder if there's another way to make this work, specially for mobile devices !
Thanks !

**Note:** With or without the plugin the Ettercap makes iphone devices useless without internet connectivity !
Even without start sniffing... it mess up with the iphone just by start ARP poisoning ...

**Comment by koeppea** [comment]
Hi

w/o knowing your exact setup, lets start with the easiest one:



> Even without start sniffing... it mess up with the iphone just by start ARP poisoning ...

when you attract traffic using a MITM technique, you have to have Sniffing running. Otherwise Ettercap doesn't forward packets.

Regarding HSTS, the behaviour whether a client us enforcing or insisting the use of HTTPS (and https:// URI's) is extremely implementation dependent.

So when you modify all https:// links with http://, and the client has either pre-defined all URLs of a website have to use HTTPS or the client has cached the URL as been https:// due to HSTS from a previous visit, it will deny loading the http:// URL. See our [wiki page for HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS) for more information.

When Ettercap is doing a MITM via ARP poisoning w/o having sslstrip plugin and having SSL interception enabled, it should be in the middle of all IPv4 traffic between the targets.

You can check if the sslstrip plugin works correctly by poisoning a Linux machine and check with curl if it only contains http:// URLs.

Nowadays it's not easy as older times to get into or circumvent encrypted traffic.

**Comment by saormart** [comment]
@koeppea, thanks for help!
Well my setup is:
Running Kali Linux release 2020.2 on Virtual Box with network configured as Bridged Adapter, Promiscuos Mode: Allow All. (Main OS: Windows 7)

My Network setup: Linksys WRT54GL (this thing is only ipv4)
Before I start ettercap, I tried with both command lines to forward the packets:
echo 1 > /proc/sys/net/ipv4/ip_forward
sysctl -w net.ipv4.ip_forward=1

Also did the recommended config on the etter.conf by set both: "ec_uid" and "ec_gid" to 0 (zero) and uncomment the 2 lines in Linux section "redir_command_on and off".

**Note:** I also had to enable the  "redir_command_on and off" for ipv6 even on ipv4 network, otherwise ettercap would crash with a fatal error: "Can't insert firewall redirects"

So, going back to the issue with iPhone:
Start ettercap in graphical mode, start sniff -> Scan for hosts -> add Target 1 (Router IPv4) -> add Target 2 (iPhone IPv4).
iPhone still with internet connectivity...
Start Arp poisoning - iPhone loose internet connectivity!
On iPhone, I'm using the Fing app to ping google dns (8.8.8.8) for internet connectivity test.

Same test, but different target (now the windows 7 pc that's hosting the kali machine):
It seems to work, I can intercept the packages and no issue by loosing internet connectivity!

Conclusion: The issue with iPhone may be something that the iOS can detect and block all the internet traffic for security issues ?
I'll try to investigate it deep by using other iOS versions (work in progress to get the devices...)
So, if I find anything useful I'll keep you updated !
Thanks!

**Comment by koeppea** [comment]
> echo 1 > /proc/sys/net/ipv4/ip_forward
> sysctl -w net.ipv4.ip_forward=1

You can omit this. This enabled Kernel Routing for foreign packets. This is turned off during startup of Ettercap, because Ettercap has to do the packet forwarding, since Ettercap should be in the middle and not the Kernel.

Especially for iPhone over wireless, it helped in the past to tune ARP poisoning. Check the ARP options in the **etter.conf** file.
Play with the `arp_poison_smart` and/or `arp_poison_request` option. You should read the man page for etter.conf carefully to understand what each of these options is doing.
