### ISSUE TITLE
Ettercap Kills Target Internet

### ISSUE THREAD

**Issue by jrmessiah** [Ettercap/ettercap#1047]
Sorted the UID to 0 and both the redir from the conf file.

Started ettercap as instructed. 

The issue is the target system can only open http and not https when ettercap is running.

Also when i tried to log into a http login, its not sniffing anything.

I mean iv been using this for over 5 yrs and this new version.......its not working as before.

Anyone can clear my noobness?

**Comment by koeppea** [comment]
Hi,

what happens if you do NOT uncomment the __redir__ lines in the conf file?

You don't have to forget that within the last 5 years, TLS and the browser security has made big steps against MITM attack vectors which are quite efficient.

For example, an up2date Firefox browser caches Certificate signatures for already visited websites during the lifetime of the seen certificate. When you then try to intercept the SSL between Firefox and a SSL webserver using a fake certificate, Firefox remembers that the signature should be different and even prevents user recourse.

There are plenty examples in the mine field of SSL interception that can make establishing a SSL connection miserably fail. But this is due to the design of the TLS related improvements.

So I'm afraid the answer to your question is not black/white (BTW like your question).

You can try with `curl -k` to check if the SSL interception is working. Is it working using curl?

Please also consider reading our [Wiki article](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) regarding providing troubleshooting information.

**Comment by jrmessiah** [comment]
> Hi,
> 
> what happens if you do NOT uncomment the **redir** lines in the conf file?
> 
> You don't have to forget that within the last 5 years, TLS and the browser security has made big steps against MITM attack vectors which are quite efficient.
> 
> For example, an up2date Firefox browser caches Certificate signatures for already visited websites during the lifetime of the seen certificate. When you then try to intercept the SSL between Firefox and a SSL webserver using a fake certificate, Firefox remembers that the signature should be different and even prevents user recourse.
Thanks for the prompt response....appreciated. And apologies for the black & white question. I think what you said makes a lot of sense....it doesnt work even if i do not uncomment the redir in the conf file.

But i am guessing its due to firefox and the signatures as you explained. I am going to try this against other browsers and will test out the curl -k

Thanks for your time!






> There are plenty examples in the mine field of SSL interception that can make establishing a SSL connection miserably fail. But this is due to the design of the TLS related improvements.
> 
> So I'm afraid the answer to your question is not black/white (BTW like your question).
> 
> You can try with `curl -k` to check if the SSL interception is working. Is it working using curl?
> 
> Please also consider reading our [Wiki article](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) regarding providing troubleshooting information.
