### ISSUE TITLE
3 Errors after running sudo Ettercap -G

### ISSUE THREAD

**Issue by Sevada797** [Ettercap/ettercap#1074]
ettercap 0.8.4-rc copyright 2001-2020 Ettercap Development Team
<h3>##This is the Error</h3>
Cannot change tcp-segmentation-offload <br></br>
Cannot change large-receive-offload<br></br>
Failed to create secure directory (/root/.config/pulse): Permission denied

**Comment by LocutusOfBorg** [comment]
does it fail to run?
we usually run it as normal user with sudo.
looks like you are running it with sudo ettercap -G but you are already root?

Which OS?

**Comment by koeppea** [comment]
The first two message appear when _ethtool_ isn't installed.
The second appears to be some implicit thing when the GNOME widgets are used.
Since ettercap by default drops it's own permissions once the privileged actions are finished, it may have not the sufficent permissions to do these implicit actions triggerd by the GNOME widgets.
This can be solved by setting **ec_uid** to 0 in _etter.conf_.
