### ISSUE TITLE
DNS wildcard override

### ISSUE THREAD

**Issue by bolegb** [Ettercap/ettercap#1077]
When using a DNS_Spoof module,  there is a problem with having this type of configuration in the etter.dns file:

test.test.somesite.com 1.2.3.4
*.test.somesite.com 5.6.7.8

It seems that the more specific instruction is being overridden by the second (wild-carded) entry, such that all DNS queries to test.test.somesite.org are being replied with 5.6.7.8

Normally, more specific instructions should be checked first, and only if there is no specific match, a more general match should be considered.

Thanks for the great work!

**Comment by koeppea** [comment]
Is it the same when you flip the order?

**Comment by bolegb** [comment]
> Is it the same when you flip the order?

Actually, when I flip it it seems to work.

Thanks.

**Comment by koeppea** [comment]
Ok I'll have a look at it.

**Comment by koeppea** [comment]
I've checked the source code.
So entries in the _etter.dns_ file specified last, are processed first.
Thatswhy it behaves as you experience.

With a bit of effort we could turn this behaviour around but this risks that it could break working _etter.dns_ files from others.

Since Ettercap is not a full-blown DNS server implementation, it does not do the more specific matching since it would add too much cost to the per-packet processing.

I think with the knowledge that the order of the entries matter and have to be ordered from the less- to the more specific entries, it should be an doable way or workaround.

Hence closing this issue.

**Comment by bolegb** [comment]
> I've checked the source code.
> So entries in the _etter.dns_ file specified last, are processed first.
> Thatswhy it behaves as you experience.
> 
> With a bit of effort we could turn this behaviour around but this risks that it could break working _etter.dns_ files from others.
> 
> Since Ettercap is not a full-blown DNS server implementation, it does not do the more specific matching since it would add too much cost to the per-packet processing.
> 
> I think with the knowledge that the order of the entries matter and have to be ordered from the less- to the more specific entries, it should be an doable way or workaround.
> 
> Hence closing this issue.

Thanks for the quick action. I agree. I think that the only thing required is updating the etter.dns file examples, so that the users will be aware of this issue.

Thanks again,
Oleg

**Comment by koeppea** [comment]
Good point. You want to raise a pull request?

**Comment by bolegb** [comment]
> Good point. You want to raise a pull request?

Sure.
