### ISSUE TITLE
SSL dissection needs a valid 'redir_command_on' script in the etter.conf file Ettercap might not work correctly. /proc/sys/net/ipv6/conf/eth0/use_tempaddr is not set to 0. Privileges dropped to EUID 65534 EGID 65534...

### ISSUE THREAD

**Issue by chisvot** [Ettercap/ettercap#1093]
My ettercap is giving me that error, i don't know what to do

**Comment by koeppea** [comment]
@chisvot These are just informational messages:

> SSL dissection needs a valid 'redir_command_on' script in the etter.conf file 
This just tells that Ettercap won't be able to intercept SSL traffic when no valid redir_command has been activated in the etter.conf file.
> Ettercap might not work correctly. /proc/sys/net/ipv6/conf/eth0/use_tempaddr is not set to 0
This is a warning if Ettercap shall do MITM using IPv6 where strange behaviour has been noticed in the past when the temporary IPv6 address are primarily used.
> Privileges dropped to EUID 65534 EGID 65534
This message just informs you, that Ettercap dropped it's own priviledges to avoiding to put the machine that runs ettercap at danger, as it's processing network traffic that potentially could lead to a crash.

Since I do not see any issue / problem, I'm closing this issue.
