### ISSUE TITLE
dhcp-spoofing: Only setting the dns-server

### ISSUE THREAD

**Issue by RoseDeSable** [Ettercap/ettercap#1111]
Good Morning,
 the attack works fine. But I want selectively handle victim's traffic. Therefore the gateway should be the real default gateway and my attacker system should only be the faking dnsserver. But I doen't find any possibility to set the gateway here: dhcp:/ip-pool/netmask/dnsserver. Can I say ettercap, that it shall adopt the default gateway from the packet of the real dhcp-server ? 
 My problem is, that in a cisco network I can't make dns-spoofing. 

Bye
Rose

**Comment by koeppea** [comment]
Sound like a cool feature.....

**Comment by RoseDeSable** [comment]
Hi,
 is the new feature implemented ?

Best Regards
Rose

**Comment by koeppea** [comment]
I tried and wrote a plug-in. But tests didn't work out when ettercap is in the client lan. The problem is that the DHCP response that need to be poisoned is a layer 2 Unikats and IP is set to the unspecified address 0.0.0.0.

ARP poison cannot attract that as layer 2 header is already set by the DHCP server.

I might give it another try and more detailed tests. Maybe the DHCP refresh message is poisonable.

**Comment by viky88** [comment]
您好,您的邮件我已经收到.

**Comment by koeppea** [comment]
Yes the last packet is the ACK packet. But the DHCP server does not perform a ARP request to find out the MAC of the client, because the client does not yet have this IP finally.
The DHCP server knows the client MAC from the DISCOVER and REQUEST packet. It just sets it as the Ethernet destination when returning the client side packets.

The interesting question is then, how can I force the packets from the DHCP server to the yet unknown client to go through the attacker maching running Ettercap? ARP poisoning is not an option as explained above.

The only way would be Bridged Sniffing, but for that, very special physical conditions have to be met like physically chaining in between the client and the switch.

As mentioned, maybe the DHCP Refresh process might be attaackable or DHCP relayed packets. This would be the direction of my further investigation.

**Comment by RoseDeSable** [comment]
Allwright,
 the gateway is in the offer packet at address 0xC0A80101 (GIADDR (Gateway IP address). This packet has a destination - the mac-address of the client. Therefore is not a broadcast and packet and ettercap cannot hear it. Is this correct ? 
 But if the attacker is in a subnet, he only hears the traffic in this part of the lan. Is he not able to find out the gateway(s) of the subnet, to set it in the falsified ack-packet ?

**Comment by RoseDeSable** [comment]
Hello,
 my idea is, to set manually the gateway. I think about an additional option in the manner "-M dhcp:/255.255.255.0/192.168.0.1/<ip of the gateway>. You can't do allthing automatically. For some things you need a greater background of the net, that you win by using additionally tools (like wireshark, yersinia ...).

**Comment by koeppea** [comment]
Understand. You want to use ettercap just to point the client to an alternative gateway instead of chaining the client traffic through ettercap. However, during the course of the issue, we drift now away from setting the dns-server option to the routers option.

However, even Ettercap is running in the same subnet, the clients are still most probably connected via a switch. And the switch sends Ethernet unicast packets to the ports the MAC has been learned, and not to the port ettercap is connected.

You could try to get the MAC address table of the switch overloaded using the _rand_flood_ plugin so that the switch begins to flood unicast packets to all ports again, but this is barely predictable. This is the challenge to win first. Getting the DHCP server response packets visible on the ettercap machine.

**Comment by koeppea** [comment]
> my idea is, to set manually the gateway.

BTW: Have you had a look to the redirect MITM technique?
