### ISSUE TITLE
ettercap not working on wsl2 ubuntu

### ISSUE THREAD

**Issue by vansh-bansal** [Ettercap/ettercap#1113]
i have a windows laptop with wsl2 enabled and have ubuntu installed on it. i installed ettercap text only on it but ettercap shows error that arp poisoning reqiuires non empty host files are required whenever i try to sniff packets

**Comment by LocutusOfBorg** [comment]
might be that promiscuous mode doesn't work in wsl?

**Comment by koeppea** [comment]
You're probably using an outdated ettercap version from your distribution.
Only the current released version 0.8.3.1 contains the fix for that issue.
I've also made a couple of videos on that: https://www.youtube.com/watch?v=fQtlmi6tqDI, https://www.youtube.com/watch?v=W3S1scJPy1Q
Please reopen the issue if this doesn't help in your case.
