### ISSUE TITLE
Ettercap intercepted the data, but failed to tamper with it

### ISSUE THREAD

**Issue by aBenup** [Ettercap/ettercap#1177]
I hope you can help me. I created an AP hotspot with a virtual machine, and the other two hosts connected to the hotspot and tampered with their data. The network card data can be sniffed successfully, but the tampering is not successful according to the filter.
The filter file is as follows：
if (ip.proto == TCP)
{
	if (tcp.dst == 8888 && search(DATA.data,"##"))
	{
		log(DATA.data,"/tmp/payload.txt");
		drop();
		execinject("/bin/python /tmp/car_login.py");
		exec("/bin/rm /tmp/payload.txt");
		msg("ok");
	}
}
The ettercap instruction is as follows：
ettercap -Tq -i ens33 -F filter.ef /192.168.1.137/ /192.168.1.109

**Comment by koeppea** [comment]
I think I doesn't understand your exact topology. Is Ettercap running on the maching that hosts the AP? If so, I wonder, why ettercap is not run in Bridge Mode, since it should just bridge between the wireless and the Ethernet interface.

Please provide more detail about the sourrounding environment. Also the version of Ettercap would be of interest.

**Comment by aBenup** [comment]
Thanks for your reply. Yes, Ettercap is running on the maching that hosts the AP. Ettercap version is 0.8.2. 
I'll try Bridge mode right away.

**Comment by aBenup** [comment]
I tried Bridge mode. But ettercap print the following statement: Error 90, Message too long. libnet_write 65549 (-1): libnet_write_link: only -1 bytes written (Message too long).
The ettercap instruction is as follows：
ettercap -B wlp4s0 -Tq -F filter.ef  /192.168.1.109/8888

**Comment by aBenup** [comment]
Thank you, koeppea. I have installed the latest version. Then I found that using UNIFIED mode can tamper with data, but it didn't forward the tampered data. Bridge mode keeps reporting that the virtual memory exhausted , even though I've expanded the size of swap.

**Comment by koeppea** [comment]
This is what I assume too.

The access point deamon is intended to forward network traffic. If the 
deamon is continuing forwarding while Ettercap is running in parallel, 
packets will be duplicated.

You need to setup the access point deamon or network configuration in a 
way, that is just broadcasts the SSID to immitate a access point, but it 
should not do traffic forwarding. Traffic forwarding would then be the 
task of Ettercap.

But I cannot tell you how to do that exactly as I have no experience to 
setup a wireless card so that it immitates an access point.

**Comment by aBenup** [comment]
Thank you very much.I'll try another way.

**Comment by koeppea** [comment]
Closing then. Good luck.
