### ISSUE TITLE
Isolate plugin rarely work?

### ISSUE THREAD

**Issue by pedro-carmine** [Ettercap/ettercap#1189]
I'm not sure if I'm using it correctly:

`sudo ettercap -TqzP /<target.ip>/ ///`

But most of the time it just says that the plugin started and doesn't actually isolate the host.

Am I missing something?

**Comment by koeppea** [comment]
I reproduced the issue.

So for me it works. However it takes some time to get effective.
The reason is because isolate plugin works on ARP layer and it needs a ARP request flying by from the victim to get poisoned.

My test case looked the following:
1. I checked the ARP cache before the attack. The correct MAC for the ping target is displayed
```
root@VM-Debian64:~# 
root@VM-Debian64:~# arp -n
Address                  HWtype  HWaddress           Flags Mask            Iface
172.21.21.1              ether   08:00:27:7e:2c:b7   C                     eth0
172.21.21.2              ether   00:26:98:ac:d2:41   C                     eth0
172.21.21.63             ether   30:9c:23:60:cc:85   C                     eth0
172.21.21.29             ether   08:00:27:ed:72:79   C                     eth0
172.21.21.45             ether   08:00:27:6d:34:03   C                     eth0
172.21.21.66             ether   30:9c:23:60:cc:85   C                     eth0
root@VM-Debian64:~# 
```

2. Ping to the target works before the attack is started.
```
root@VM-Debian64:~# 
root@VM-Debian64:~# ping -c4 vm-freebsd64
PING vm-freebsd64.fritz.box (172.21.21.29) 56(84) bytes of data.
64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=1 ttl=64 time=0.620 ms
64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=2 ttl=64 time=1.05 ms
64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=3 ttl=64 time=0.936 ms
64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=4 ttl=64 time=0.856 ms

--- vm-freebsd64.fritz.box ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 8ms
rtt min/avg/max/mdev = 0.620/0.866/1.054/0.161 ms
root@VM-Debian64:~# 
root@VM-Debian64:~# 
```
3. Then I started the attack.
4. The ARP cache still contains the correct MAC address
5. Then I pinged again the target which was successful as well. But this triggered the ARP cache to get refreshed and isolate plugin kicked in and poisoned the victim.
```
isolate: 172.21.21.29 added to the list
isolate: 172.21.21.1 added to the list
```

6. Showing the ARP cache shows now another MAC address for the ping target.
```
root@VM-Debian64:~# arp -n
Address                  HWtype  HWaddress           Flags Mask            Iface
172.21.21.1              ether   08:00:27:7e:2c:b7   C                     eth0
172.21.21.2              ether   00:26:98:ac:d2:41   C                     eth0
172.21.21.63             ether   30:9c:23:60:cc:85   C                     eth0
172.21.21.29             ether   08:00:27:7e:2c:b7   C                     eth0
172.21.21.45             ether   08:00:27:6d:34:03   C                     eth0
172.21.21.66             ether   30:9c:23:60:cc:85   C                     eth0
root@VM-Debian64:~# 
```

7. Ping doesn't work anymore.
```
root@VM-Debian64:~# ping -c4 vm-freebsd64
PING vm-freebsd64.fritz.box (172.21.21.29) 56(84) bytes of data.

--- vm-freebsd64.fritz.box ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 83ms

root@VM-Debian64:~# 
```


So in general it works for me however it needs a ARP request to poison which could take a bit until the plugin becomes effective.

**Comment by pedro-carmine** [comment]
> I reproduced the issue.
> 
> So for me it works. However it takes some time to get effective. The reason is because isolate plugin works on ARP layer and it needs a ARP request flying by from the victim to get poisoned.
> 
> My test case looked the following:
> 
> 1. I checked the ARP cache before the attack. The correct MAC for the ping target is displayed
> 
> ```
> root@VM-Debian64:~# 
> root@VM-Debian64:~# arp -n
> Address                  HWtype  HWaddress           Flags Mask            Iface
> 172.21.21.1              ether   08:00:27:7e:2c:b7   C                     eth0
> 172.21.21.2              ether   00:26:98:ac:d2:41   C                     eth0
> 172.21.21.63             ether   30:9c:23:60:cc:85   C                     eth0
> 172.21.21.29             ether   08:00:27:ed:72:79   C                     eth0
> 172.21.21.45             ether   08:00:27:6d:34:03   C                     eth0
> 172.21.21.66             ether   30:9c:23:60:cc:85   C                     eth0
> root@VM-Debian64:~# 
> ```
> 
> 2. Ping to the target works before the attack is started.
> 
> ```
> root@VM-Debian64:~# 
> root@VM-Debian64:~# ping -c4 vm-freebsd64
> PING vm-freebsd64.fritz.box (172.21.21.29) 56(84) bytes of data.
> 64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=1 ttl=64 time=0.620 ms
> 64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=2 ttl=64 time=1.05 ms
> 64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=3 ttl=64 time=0.936 ms
> 64 bytes from VM-FreeBSD64.fritz.box (172.21.21.29): icmp_seq=4 ttl=64 time=0.856 ms
> 
> --- vm-freebsd64.fritz.box ping statistics ---
> 4 packets transmitted, 4 received, 0% packet loss, time 8ms
> rtt min/avg/max/mdev = 0.620/0.866/1.054/0.161 ms
> root@VM-Debian64:~# 
> root@VM-Debian64:~# 
> ```
> 
> 3. Then I started the attack.
> 4. The ARP cache still contains the correct MAC address
> 5. Then I pinged again the target which was successful as well. But this triggered the ARP cache to get refreshed and isolate plugin kicked in and poisoned the victim.
> 
> ```
> isolate: 172.21.21.29 added to the list
> isolate: 172.21.21.1 added to the list
> ```
> 
> 6. Showing the ARP cache shows now another MAC address for the ping target.
> 
> ```
> root@VM-Debian64:~# arp -n
> Address                  HWtype  HWaddress           Flags Mask            Iface
> 172.21.21.1              ether   08:00:27:7e:2c:b7   C                     eth0
> 172.21.21.2              ether   00:26:98:ac:d2:41   C                     eth0
> 172.21.21.63             ether   30:9c:23:60:cc:85   C                     eth0
> 172.21.21.29             ether   08:00:27:7e:2c:b7   C                     eth0
> 172.21.21.45             ether   08:00:27:6d:34:03   C                     eth0
> 172.21.21.66             ether   30:9c:23:60:cc:85   C                     eth0
> root@VM-Debian64:~# 
> ```
> 
> 7. Ping doesn't work anymore.
> 
> ```
> root@VM-Debian64:~# ping -c4 vm-freebsd64
> PING vm-freebsd64.fritz.box (172.21.21.29) 56(84) bytes of data.
> 
> --- vm-freebsd64.fritz.box ping statistics ---
> 4 packets transmitted, 0 received, 100% packet loss, time 83ms
> 
> root@VM-Debian64:~# 
> ```
> 
> So in general it works for me however it needs a ARP request to poison which could take a bit until the plugin becomes effective.

Thanks for the detailed explanation, you are very right!

Let's say that I want to isolate the device that I mentioned with the default gateway of the LAN, it would require an ARP between those two devices?

Example command: `sudo ettercap -TqzP /<target.ip>/ /<default_gateway.ip>//`

**Comment by koeppea** [comment]
With this command, you poison only the communication between the victim and the router. All other intra-LAN communication will not be poisoned.

However it still requires the victim to send an ARP request asking for the MAC address of the router's IP address. Also since this is a broadcast, the ettercap attacker and the router is receiving this request. It's now a race condition which potentially could be won by the router. However once the active ARP request has been seen, isolate plugin doesn't stop sending poisoned ARP replies to the victim, so that even the router may have won the race condition, the isolate plugin by the attacker will push through at some time (I would guess some seconds).

**Comment by pedro-carmine** [comment]
Got it. Thanks once again, I'll close this issue.
