### ISSUE TITLE
question ettercap

### ISSUE THREAD

**Issue by rimeh** [Ettercap/ettercap#662]
Hello,

I have a project that consite to create a program that protects a box (linux os) against the different types of attack.
I began to understand the different type of attack MITM example , ARP spoofing ... .
I download ettercap,now I want understand the code but I find more files.   I do not know what I should start.
Please can help me to understand the ettercap code or give me a link that contains a code that allows to security  against the different type of attack as MITM , sniffer, ARP spoofing ....

Thank you .

**Comment by koeppea** [comment]
Hello @rimeh,

would you mind rephrasing your initial text into English?

Thanks.

**Comment by LocutusOfBorg** [comment]
I guess french is understood only by me :-)

**Comment by rimeh** [comment]
OK pas de pb ,
merci por votre remarque .

2015-02-25 16:54 GMT+01:00 Gianfranco Costamagna <notifications@github.com>:

**Comment by LocutusOfBorg** [comment]
(BTW I'm not a native french speaker, just I can translate something to you if you don't get completely the answer)

If you want to *protect* you network you can use some ettercap plugins such as "arp cop" "find ettercap" and so on, the code is in "plugins/plugin name/plugin name.c"
ettercap has an internal library, so the underlying code will be found in src/ec_*.c functions (such as ec_send and ec_hook).

BTW if you want to protect yourself from arp spoofing attacks you might find many arp watchers for linux too directly online, using ettercap code might be not fully understandable due to its complexity.

**Comment by rimeh** [comment]
Thank you very much LOctusOfBorg for your reply but I have to write code that analyzes the network and detects the level of ARP attacks 2 so I have to understand a little of the code ettercapand that I can write a code.
Yes I know there are commands linux that scans the network and detects the type of spoofing attack , but my goal is realize a code.

**Comment by LocutusOfBorg** [comment]
you can then use something like the plugin mentioned above with the libettercap library!
