### ISSUE TITLE
Ettercap, SSLstrip and site certificate issues

### ISSUE THREAD

**Issue by paktiger** [Ettercap/ettercap#688]
I have tested ettercap and sslstrip in my own network to sniff password, however, I am unable to get any kind of information rather I have got error on my chrome about site certificate. That my connection to sever is not secure and page becomes blank. I am using latest kali Linux and latest ettercap. On victim machine i am using latest google chrome. I have done all setting which have been mentioned on different tutorials, all the settings are fine, however, its chromes latest security that wont allow me to sniff. Please guide me

**Comment by koeppea** [comment]
Have you also checked with the latest version build from github?
Have you closed and reopened the browser after you started the ettercap MITM?
Which website are you trying to intercept?

**Comment by koeppea** [comment]
Ping

**Comment by paktiger** [comment]
yes I have done what you said. SSLstrip wont work on https

**Comment by birdofprey** [comment]
good tools

**Comment by paktiger** [comment]
what is the new ways to strip SSL?

**Comment by koeppea** [comment]
OK first of all, intercepting SSL w/o having access to the trust store of the client becomes extremely difficult. Reason are the improved standards and their extensions like HSTS.
Famous websites like facebook, google, yahoo, and many more, have made it onto browser's build-in list that doesn't act on HTTP at all even though you type *http://www.facebook.com* and breaks at any certificate issue without the possibility of user recourse.

So you need to really really know some background and it may not be possible at all due to the said above.

Second, since you're mentioning SSLStrip, it's not clear what you mean, since ettercap has a plugin called sslstrip that does somthing completely different than intercepting a SSL connection.

Third, you haven't provide any kind of detail.
 1. do you mean sslstrip plugin?
 2. what is the website you're testing with
 3. how does your etter.conf look like
 4. provide the *ettercap_debug.log* file

So concluding, it's not clear to me, what you actually want.

**Comment by paktiger** [comment]
Dear Sir,

Thank you for your reply, however, I want to intercept facebook or whatsapp traffic in fully readable form. But as you said its near impossible, so there is no point of discussion.

**Comment by koeppea** [comment]
So can we close this issue?

**Comment by paktiger** [comment]
no but i wanna know what are the possible ways to intercept any messenger messages before they are encrypted ?

**Comment by koeppea** [comment]
I'd suggest you write a software that links to the input libraries of the devices. Maybe NSA or BND has an better answer.
Closing this issue, as it becomes unrelated to Ettercap.
