### ISSUE TITLE
Problem When Trying to modify Big files

### ISSUE THREAD

**Issue by HamzaKo** [Ettercap/ettercap#725]
Hello,
I'm trying to modify compressed files on the fly. For example: User "**A**" will send a zipped file to Server "**Z**", I'm trying to modify the **content of the zipped file** then send it back to Server "**Z**". 

I tried to use ettercap filter but since the zipped file is large, it will be splitted into several chunks, and my filter will receive a chunk each time. **Can i force ettercap to call my filter only when all the chunks are received?** _so i can decompress the file modify it then send it again. _

**Comment by LocutusOfBorg** [comment]
Hi, I think I remember some implementation about this on the latest git head, did you try to build it from source?

G.

**Comment by HamzaKo** [comment]
Yes i did but there was no difference, help ???

**Comment by koeppea** [comment]
I'm afraid the use case, from what I understood, is not possible.
ettercap is primarily designed to do MITM and for a successful MITM attack, the victim should not recognize that.

Buffering such huge amount of packets would result in a very odd or even timeout situation from a TCP standpoint.

Due to this constraint, ettercap can act on very little pieces only.

**Comment by HamzaKo** [comment]
Thanks for help,
I may need to find another way to do it.
