### ISSUE TITLE
How can i use ettercap on a gateway to filter packet

### ISSUE THREAD

**Issue by KevinWL** [Ettercap/ettercap#751]
### hello,
i want to run ettercap on my raspberry pi3,and clients connet it through wilrless,but there are some problems.
i found that if i used it with option "-u"  i can't filter the packet,but if i used wihout that option then clients were disconnected .
if there is a mothod that is useful in this environment.

thanks.

**Comment by v1s1t0r1sh3r3** [comment]
Hi, I think you are talking about the Evil Twin attack with sniffing. Ok, the ettercap is launched by script with "-u" because the forwarding is done by the script externally to ettercap doing "cat 1 > /proc/sys/net/ipv4/ip_forward".

If you launch the ettercap without the -u, ettercap does the forwarding... but the script uses -u because as I said, the forwarding is done externally... that is not a problem because ettercap is doing inside the script in the appropiate way. If you want to launch ettercap externally launching "only ap" evil twin attack you must use "-u"... I recommend to you to let the script use on its way... it knows how to do it and it should be working.

Which operating system do you have on raspberry pi? raspbian 7 or 8? kali? I'll test and I'll test on both and be back to you.

**Comment by KevinWL** [comment]
Thanks for v1s1t0r1sh3r3 's suggest
I am sure it's useless.when  i trun on ip_forward ,the filter is not useful.
did you ever try the plugin "sslstrip"?

**Comment by v1s1t0r1sh3r3** [comment]
Yes. I used successfully ettercap with sslstrip. As I said I use forwarding outside ettercap using cat 1 > /proc/sys/net/upv4/ip_forward and I launch ettercap with -u and it works.

I made a script using all of this (ettercap + sslstrip) in an evil twin attack. You can check it and check the code to see the iptables rules I use etc... is here: 
[https://github.com/v1s1t0r1sh3r3/airgeddon](url)

Check it out and you will see how ettercap works perfectly and with sslstrip too... but sslstrip depends of many variables... if the "victim" uses well built bookmarks using "https://..." there is nothing to do unless you combine with something more complicated like delorean attack... if he uses bookmarks (or writing directly on url bar) something like "outlook.com" (for example)... it asks for http site, not https. Then the site is going to redirect you to https using HSTS but sslstrip uses that http request to be in the middle and to serve the page on plain to the victim and perform the https connection to the page itself (I mean sslstrip).

Good luck!

**Comment by sgeto** [comment]
I didn't understand your issue. Sorry
