### ISSUE TITLE
FATAL: Cannot open * for writing

### ISSUE THREAD

**Issue by hktalent** [Ettercap/ettercap#752]
sudo ettercap -i en0 -k /Users/xiatian/allHosts.txt -Tq

is error :
ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Listening on:
   en0 -> B8:E8:56:02:4E:8C
	  192.168.29.211/255.255.254.0
	  fe80::bae8:56ff:fe02:4e8c/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20388 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Randomizing 511 hosts for scanning...
Scanning the whole netmask for 511 hosts...
* |==================================================>| 100.00 %

DHCP: [20:16:D8:F5:C3:00] REQUEST 192.168.29.55
203 hosts added to the hosts list...

FATAL: Cannot open /Users/ok/allHosts.txt for writing

**Comment by koeppea** [comment]
Hi,

this is due to the dropping of privileges after the privileged actions have been done.
The EUID and GUID ettercap is dropping to are configured in the **etter.conf** and default to the UID of the *nobody* user:
```
[privs]
ec_uid = 65534                # nobody is the default
ec_gid = 65534                # nobody is the default
```
So you can change these values to **0** which is anyway required if you perform SSL interception. This way the file you want to create in your home directory would by owned by *root*.
If you want the file being owned by your actual user, you need to find out your EUID/GUID using the command `id` and set these numbers for _ec_uid_ and _ec_gid_ in the **etter.conf**.
