### ISSUE TITLE
ETTERCAP eth.proto not working

### ISSUE THREAD

**Issue by crange8** [Ettercap/ettercap#759]
Hi,
I'm creating a simple filter in order to recognize when ettercap receives an ARP file. But it is never working
The code is:
```
if (eth.proto == ARP) {
      msg("true..\n");
}
```
I checked with wireshark and it is receiving ARP, UDP data.
Also when I check:
```
if (eth.proto == IP) {
      msg("true..\n");
}
```
The console sends true as messages because there are UDPs, but when I try with ARP there is not response.
Can anyone help me please.

**Comment by koeppea** [comment]
Hi @crange8 

Sorry for reacting that late. I don't have a solution for you, since the behavior is somewhat "desirable".
The reason for that lies in the ARP protocol decoder. Because it does not trigger the APP_LAYER data_decoder thread because ARP has no payload or upper-layer protocols stacked. 
In this data_decoder thread, the filter engine is accessed.
In contrast, the TCP and UDP decoder, do trigger this thread:
https://github.com/Ettercap/ettercap/blob/5c84af443d295b68de42effb32cfcdc3954c5d4c/src/protocols/ec_tcp.c#L293

Why I don't have a solution: Because normally it's not desirable to run through the filter for each ARP packet which Ettercap relies on to win the race to successfully poison the targets.

I also cannot think of a use-case.

So closing without a solution. Hope the explanation is satisfying anyway.
