### ISSUE TITLE
DNS_spoof plugin Unable to redirect Victim to a specific website

### ISSUE THREAD

**Issue by 5p3c7r3** [Ettercap/ettercap#765]
The network scan in Ettercap v0.8.2 detected the victim pc which is my Windows 7 machine  and my internet gateway which is my router so I set my target 1 as the victim machine and target 2 as the router and proceeded to ARP poison them and Activated the DNS_spoof plugin however when I switch over to my victim machine ,the windows 7 with Google chrome and visited google.com I get an “NET:ERR_CERT_AUTHORITY_INVALID” {the your connection is not private error} but when I goto an ‘http’ website I was able to enter without any error now I know that the browser is recognising the ARP poison but the problem is when I visit http://www.addictinggames.com/  it successfully redirected to my rogue website but when I goto another website http it failed to display my website

I’am running this in kali linux 2016.2

Please tell me what I’am doing wrong or verify this is a bug

**Comment by sgeto** [comment]
no bug. you can't redirect https traffic without getting an SSL/TLS error on the victim's machine. And if the victim has previously connected to a site using https the browser will remember it and won't downgrade to http.  Chrome even hardens it by not allowing you to add exceptions for certain domains (including their owns)

**Comment by Spyro289** [comment]
Thanks for your clarification
what about when i was able to redirect  http://www.addictinggames.com/ but not opther  http sites

**Comment by koeppea** [comment]
This is due to the built in list of HSTS web sites.

As of now I don't know of any way to get into such a SSL session.

I recommend to manually replace the redirect rule from "any" to  specific or to do without redirection at all.

**Comment by koeppea** [comment]
Which  platform is running ettercap?

**Comment by sgeto** [comment]
@koeppea can't you just get rid of the policy by removing the header field "Strict-Transport-Security" via a filter?

**Comment by Spyro289** [comment]
I'am running it on kali linux 2016.2

**Comment by koeppea** [comment]
In theory yes. The first dependency is that you get the first visit. If the browser recognizes the site being forced to HTTPS it caches this info and the second visit will be HTTPS right away even if you type http://. 
The second dependency is that  many browsers have a hard coded list of websites that are enforced to HTTPS. E.g. Facebook, Google and Yahoo. There is no way strip the header in the initial HTTP response.
Even more difficult to get into such a HTTPS session is the fact that the browser let the user no choice to override the security warning for HSTS websites.
The RFC is worth to read. Let me know if I missed a chance.

**Comment by sgeto** [comment]
I remembered something.

My approach around it was to fool the victim's browser into thinking the websites' states have changed. You can do this by either injecting a 302 (sometimes 307) or 401 status into the response, or reply with a custom response carrying this code altogether. 

The response code to choose depends on your setup. They all convince the browser to clear the cached HSTS entry as well as loosen security on hard coded URLs.
For the hard coded URLs (facebook, google etc) who still demand a secure connection, you will also need to present a somewhat valid certificate (self-signed or spoofed is fine) for this to work.

So far, all browsers I tested fall for this. Those that go for https right away will warn you about the weird but valid certificate, but will also allow you to "proceed and ignore the warning".

**Comment by koeppea** [comment]
Mhh nice trick with the response code. Will think this through...
Maybe you mind to hand in a pull request?

**Comment by sgeto** [comment]
I'm actually just a network administrator not a programmer in the real sense. And I never done a pull request before. I'd be happy to help though. How would I do this and what is required?

**Comment by Spyro289** [comment]
sgeto & koeppea would you kindly list the steps to Bypass HSTS using Debian jessie or in Kali linux
Your help is greatly appreciated

**Comment by sgeto** [comment]
There's no foolproof way yet. But I try to guide you a little. Can you give me more information about your setup? Commands and programs and configurations you are using...

**Comment by Spyro289** [comment]
Sure i'am using the OS Kali linux 2016.2
I'am  running Ettercap GUI 
this is my ettercap.dns file:

[etter.dns.txt](https://github.com/Ettercap/ettercap/files/559883/etter.dns.txt

And this is my conf file
[etter.conf.txt](https://github.com/Ettercap/ettercap/files/559886/etter.conf.txt)

**Comment by sgeto** [comment]
Pretty generic configs. They seem fine. An unrelated advice would be to uncomment all Microsoft domains since you're intending to spoof every DNS query.

I am not home right now, but I can tell you right away that my advice involves creating  custom responses. There are many ways but Apache's rewrite module should be enough for you since you're hosting websites locally. You can ask Google about it, or me again in a few hours. :-D

**Comment by koeppea** [comment]
HSTS or RFC6797 has been designed not to be bypassed or circumvented.

**Comment by koeppea** [comment]
> My approach around it was to fool the victim's browser into thinking the websites' states have changed. You can do this by either injecting a 302 (sometimes 307) or 401 status into the response, or reply with a custom response carrying this code altogether.

Have you tested this? I didn't found a caveat in the RFC that matches your suggestion.



> They all convince the browser to clear the cached HSTS entry as well as loosen security on hard coded URLs.

I only can read that a successful "secure" connection is able to modify the cached HSTS information. Especially the section [No User Recourse](https://tools.ietf.org/html/rfc6797#section-12.2) and [HSTS Pre-Loaded List](https://tools.ietf.org/html/rfc6797#section-12.3) makes me suspicious.

**Comment by Spyro289** [comment]
Sure please lead the way, sgeto

**Comment by koeppea** [comment]
> There's no foolproof way yet.

As you already mentioned there is no recipe to succeed this.
The only chance you have is to get the first unencrypted HTTP dialog to strip away the "*Strict-Transport-Security*" response header. To achieve this, you need to have the **sslstrip** plugin running.

Unfortunately I still know no way for pre-loaded listed websites or sucessfully cached websites despite owning a valid CA certificate w/ private key that the client browser trusts. 

The approach to inject another HTTP response code would only work for a HTTP connection but this only applies for non or not-yet cached HSTS websites. Any attempt to break into the secure connection will most probably result in the [No User Recourse](
https://tools.ietf.org/html/rfc6797#section-12.2) described behaviour, thus the HTTP(S) dialog wont suceed before the response code could have become modified.

**Comment by sgeto** [comment]
It'm not sure what exact condition is necessary to achieve it, but it's possible. Even with hard coded or cached addresses. And even without have to be the first. I does however sometimes take a few "manual reloads" to convince a browser. I will have a closer look of the RFC paper.
I tried to recreate it this morning but there was something wrong with my windows 10 work station. I was however able to redirect three of my smartphones'. I am a 100% certain that my desktop had fallen for it too.
The URL https://paxadiutor.blogspot.com/  for example is my personal blog I visit all the time. Yet every browers (stock, firefox and chrome) proceeded and allowed me to ignore the self-signed certificate. I used a 401 response in all cases. The different browsers seem to handle the code differently. There doesn't seem to be a uniform procedure. Chrome seems to care much more about it's own domains (many manual reloads required), whereas Firefox doesn't seem to have google domains hard coded at all (no need for a certificate in my case).

please see the pcap files and screenshots I took this morning [here](https://1drv.ms/f/s!AsbijvwHoSaBrkGB-5u_LZ5KAWqx)

It's rather meager, I know. I'll try again later when my laptop boots again.

**Comment by sgeto** [comment]
@Spyro289 :
try this:

 1. Edit` apache2.conf` and set all `AllowOverride` from None to All
 2. enable rewrite module: `sudo a2enmod rewrite`
 3. create a new file with the name `.htaccess` and paste the follwing code (adjust to your needs) :
`# The condition and rule is that if the file or folder doesn't exist or the request does not match index.html it will redirect whatever to it

# Web Directory
RewriteBase /

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.html [R=302,L]`

 4. Restart apache2 service: service apache2 restart

Good luck

**Comment by Spyro289** [comment]
@sgeto  
Can u please show an example of you .htaccess

**Comment by sgeto** [comment]
An example would be the one you're seeing in step three (after the colon).

**Comment by sgeto** [comment]
@koeppea  The 'no user recourse' behavior, where certificate errors or warnings cause a connection termination, should normally happen, but when presenting a certificate it somehow doesn't.

[Here](https://1drv.ms/u/s!AsbijvwHoSaBrlgGCx8Le9TBO_12) is the pcap file of a much better attempt. I removed unnecessary packets (broadcast, DHCP, etc.) to make it cleaner.
Here's the scenario:

I created a wireless hotspot with no DHCP and DNS server. Obviously there's no internet connectivity either. The PC hosting the hotspot (10.42.0.1  c4:46:19:70:21:e7) is running ettercap and Responder (a python script that handles responses)

Ettercap command used:

ettercap -zTqi wlan0 -P dns_spoof -M dhcp:10.42.0.2-255/255.255.255.0/10.42.0.1

Responder command used:

Responder.py -I wlan0 -wfvFbr --lm		<--- over the top, I know (I wanted it to handle EVERY single response)


After that I launched the wireshark capture and connected a client (10.42.0.2  00:37:6d:61:38:05). Ettercap did the DHCP and DNS spoofing and Responder handled the rest (http/https with a 402 response and fake Certificate).

I launched Chrome and connected to Google (start packet no 179), then to Facebook (start packet no 322) and then launched Firefox and opened Wikipedia (start packet no 734) and finally Facebook (start packet no 1000) again. All of them giving the same results as they did this morning. They all go for the ssl handshake stop at the unknown CA alert and give me the option to ignore it, even though the paper says, "the user should not be presented with a dialog giving her the option to proceed".


What is weird is that I use Chrome to connect to Google and Facebook all the time yet it still followed the spoof redirection. It should now that something is not right. Maybe that's because of theresponse code that is not consider a "real error" or maybe some browsers don't follow RFC recommendations/standards so strictly. Any ideas?

**Comment by Spyro289** [comment]
Sorry guys i may not be able to get back to you guys in a few weeks i have exams coming up so i won't be able to experiment with this

**Comment by koeppea** [comment]
@sgeto mhh to me the packet capture doesn't look like containing a successful intercepted SSL session around the places pointed to above.

**Comment by sgeto** [comment]
Yes that's because I didn't "proceed". The ssl handshake is interrupted with `TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Certificate Unknown)` as you will find all over the capture (no. 252, 262, 278, 289 ect)

This interruption present the user with a warning that they can ignore rather than terminating the session (see screenshots).

**Comment by Spyro289** [comment]
1.  where do i put the .htaccess
2. is this correct:
```
RewriteBase /
RewriteEngine on
RewriteCond %{http://192.168.1.2} !-d
RewriteCond %{http://192.168.1.2} !-f
RewriteRule . index.html [R=302,L]
```

**Comment by sgeto** [comment]
Lol

First, you'd put it in the root of your Apache webserver (probably var/www/html)
Why would you modify it like that? If you want to edit it, you need to take a look at the documentation. Read about it, man! But frist try it as it is because this may already be enough for what you need. Cheers

**Comment by Spyro289** [comment]
I don't know i'am a noob can you show me an example i'am redirecting on a local network therefore my website URL: Is `http://192.168.1.2`

**Comment by sgeto** [comment]
Everyone is a "noob" in something. That however doesn't excuse the fact that you don't want to go out and inform yourself. I and koeppea have given you suggestions how you could possibly counter your issue, while at the same time saying that Ettercap doesn't provide a straightforward solution yet. My advice even goes beyond Ettercap and requires you to read up about Apache's rewrite [module](http://httpd.apache.org/docs/current/mod/mod_rewrite.html) so as to know how to use it and to configure it properly. 
Read our previous comments. And if that doesn't help you consult Apache's documentation as well as others that teach and explain what your issue is all about. And if that's too much then I'm afraid it's not going to happen. Good luck.

**Comment by Spyro289** [comment]
OK i'am only able to redirect some more `http` based websites but not all of them strange i left the .htaccess as:

```
RewriteBase /

RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-d

RewriteCond %{REQUEST_FILENAME} !-f

RewriteRule . index.html [R=302,L]
```

**Comment by sgeto** [comment]
What websites do NOT work? Google? Facebook?

**Comment by Spyro289** [comment]
I was unable to redirect:

```
http://www.bgames.com/

http://web.airdroid.com/
```

While I was able to redirect:

```
http://www.keyboardingonline.com

http://au.webs.com/

http://seventorrents.win/

http://www.brighthub.com/

http://cool-addicting-math-games.com/

http://www.addictinggames.com/
```

**Comment by sgeto** [comment]
http://www.bgames.com is redirected to http://m.bgames.com so you might wanna add it to your etter.dns
And http://web.airdroid.com too

**Comment by Spyro289** [comment]
but my etter.dns has 

 `* A 192.168.1.4 `
doesn't that mean redirect all dns to 192.168.1.4's Website

**Comment by sgeto** [comment]
All "A" records, yes. The issue is not HSTS related since both domains don't demand a secure connection. Try clearing your browser cache so something ( also type `chrome://net-internals/#dns` into your browser's address bar and check and maybe clear there too)

**Comment by koeppea** [comment]
Not to forget that some OSs by default use a local DNS cache like Windows for example.
Some Linux distros use a similar mechanism based on _nscd_ or _sssd_.
So to get proper testing result you should prior testing clear the cache on you victim's machine.
You should also see in the messages pane if and which DNS name has been spoofed.

**Comment by sgeto** [comment]
In windows, the appropriate command to clear the DNS cache would be `ipconfig /flushdns`

**Comment by Spyro289** [comment]
I've tried that though every test I do i always do that

**Comment by Spyro289** [comment]
I shter away to redirect the victim without having to clear the DNS cache of the victim

**Comment by Octoberr** [comment]
It is really dangerous to live in this world,our information is so easy to get.

**Comment by sgeto** [comment]
@Octoberr Stay safe, buddy.

@5p3c7r3 I think we're done here. Feel free to reopen if there's anythink else.
