### ISSUE TITLE
BRIDGED MODE ERROR 90: MESSAGE TOO LONG?

### ISSUE THREAD

**Issue by ngodai** [Ettercap/ettercap#772]
When I ran ettercap in bridged sniff mode, using command line:
ettercap -TqS -i eth0 -B eth1
and replace picture or use plugin dns_spoof. After few minutes, it send me an error:

ERROR : 90, Message too long
[/root/ettercap/src/ec_send.c:send_to_iface:151]

 libnet_write 1534 (-1): libnet_write_link(): only -1 bytes written (Message too long)

I read issue #245 , but I don't know it same or not?
I already got lastest version from github!

**Comment by koeppea** [comment]
Your modified packet got too long to fit your underlying link layer.
Standard Ethernet supports only 1518 bytes of total frame length.

For dns_spoof'ing, exceeding the maximum transfer unit is not typical as the data per packet is typical below 512 bytes. However, in some environments response packets may become very large. But still, getting this error for sending a spoofed DNS response, the actual response must have been defined insanely.

**Comment by LocutusOfBorg** [comment]
@koeppea maybe we should check the length before using libnet_build_data?

**Comment by koeppea** [comment]
Would be an idea. But what if length exceeds MTU? Drop?

**Comment by LocutusOfBorg** [comment]
Warning and drop should be good, we should get the current MTU size with some code
``` u_int16 get_iface_mtu(const char *iface) ``` is already there.
We should already have it in ``` iface_env ```

**Comment by koeppea** [comment]
Sounds good.

**Comment by r0bag** [comment]
I am trying to perform a bridge sniffing with ettercap. My configuration is:
win10(victim)<-->kali2016.2(mitm)<-->centos7(server)...all in VM and all on a local network.
The problem is that the bridged sniffing does not even start, respectively starts but not on the available interfaces, with the correct IP address, which you define by the command:
ettercap -Tq -i eth1 -B eth2 (eth1 and eth2 is used as local interfaces for kali, eth0 is used for the Internet) by me eth1 and eth2 are 192168.56.102 and 103. However, the sniffing starts on 192.168.56.101 and 105...besides, the Internet connections drops, as it is also described here:
https://forums.kali.org/showthread.php?18988-Ettercap-bridge-mode-on-a-gateway-box-not-forwarding-traffic
Could you please verify this?

**Comment by r0bag** [comment]
The ip problem was on my side. In kali it is not the best way to setup the static ip addresses with the gui.. However, even after correcting this flaw, 
![screenshot from 2017-01-12 10-11-26](https://cloud.githubusercontent.com/assets/18007694/21883543/097ffa9c-d8b0-11e6-9ff6-f737924d9b74.png)
it is not working :-/...

**Comment by koeppea** [comment]
> it is not working :-/...

looking at the screenshot you've provided, what isn't working.
However, since you've configured both interface within the same IP subnet (which is usually not possible as it doesn't make sense), the operating system doesn't know which one is actually the right one.

**Comment by r0bag** [comment]
https://pontus.ullgren.com/view/Multiple_interfaces_on_the_same_subnet and
http://lartc.org/howto/index.html
I would disagree with you that it does not make any sense.
However, my setup was not complete...I will try this out once more..

**Comment by cabelito** [comment]
I would like to ask is it normal if I only replace(this,that) and they are the same lenght , should it also crash with the same error - Message too long ? I understand if I replace(thing,something) that it may become bigger than the MTU but if replacing same size/lenght in bytes then what seems to be the problem ? Basicly the problem is that ettercap crashes, and stops forwarding traffic, other than that I am fine even with dropping packet.

**Comment by Nyrroz** [comment]
mute the thread

**Comment by koeppea** [comment]
@Nyrroz you're free to unsubscribe from this issue.
I confirm it's still relevant. Focussing now on it

**Comment by koeppea** [comment]
I think I understand the cause of the issue and hopefully fixed it also.
@ngodai or somebody else: can you please try if pull request #905 fixes this issue?

**Comment by koeppea** [comment]
See pull-request #905 for resolution message.
