### ISSUE TITLE
Autoadd plugin is not working with --only-mitm option

### ISSUE THREAD

**Issue by waqas-latif** [Ettercap/ettercap#780]
When ettercap is executed with --only-mitm flag, it poisons the current hostlist but does not add newly connected device into hostlist. it does not show usermsg prompts on screen in auto_add plugin. Looks like autoadd plugin is not even executed in -o mode.
any help or pointer on what might be the issue?

**Comment by sgeto** [comment]
The autoadd plugin adds new hosts to the list as they are found on the network. That obviously only works in conjunction with sniffing. Sniffing is how Ettercap would see new hosts.
The -o option may not be what you're looking for.

**Comment by waqas-latif** [comment]
I just want to arp poison the network and auto add any newly connected devices. I dont want any additional packet parsing or dissection. -M mode seems to dissect and process packet which could be very resource intensive. It starts a number of threads and the capture thread seems to take 25% of cpu usage.

**Comment by sgeto** [comment]
I don't think this can be split. Not without rebuilding it at least. Sniffing and dissection must happen for autoadd to work. You can add the -q option so that your terminal doesn't print everything it sees.
What high CPU consumption is concerned: I saw that too but I'm not sure what's exactly causing this. Maybe one of the dissectors or a dependency is going haywire. If you're adventures, you can rebuild Ettercap again and gradually exclude/update components in order to see who's the culprit (or do whatever other kind of debugging you prefer). If you can't, then I'm afraid that's the price you pay for using autoadd.
