### ISSUE TITLE
Send L3 error ettercap 0.8.2 

### ISSUE THREAD

**Issue by mr-robot92** [Ettercap/ettercap#802]
what is the error "SEND L3 ERROR : 64 byte packet (86dd:3a) destined to ff02::1 was not forwarded (libnet..write..raw..ipv6() -1 bytes written" ? how to fix this problem?

**Comment by LocutusOfBorg** [comment]
hello, did you try the latest git master?

**Comment by koeppea** [comment]
This can be typically ignored.
The packet that couldn't be forwarded is a IPv6/ICMPv6 packet destined to the *all-nodes* multicast address.
Since this destination is attached on all interfaces, forwarding using the routing decision of the kernel doesn't work. The packet arrived on your machine by design and not as a result of MITM, because somebody performed a kind of broadcast ping (`ping6 -Ieth0 ff02::1`).

**Comment by mr-robot92** [comment]
![schermata da 2017-06-02 10-52-10](https://cloud.githubusercontent.com/assets/29011980/26718532/999343c4-4781-11e7-93c8-112a4d16f3eb.png)

**Comment by LocutusOfBorg** [comment]
error message says "impossible to assign the requested address", not sure why, but at the end it shouldn't be an issue, if I understand correctly what @koeppea said above
