### ISSUE TITLE
how to install on kali linux 2017.1

### ISSUE THREAD

**Issue by shlauy** [Ettercap/ettercap#811]
hello 

**ettercap was not working well with me 
then I removed it to do reinstall but i couldn't install it**

_**(using kali linux 2017.1)**_

**- i did** 
**$ sudo apt-get install ettercap-graphical**

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package ettercap-graphical is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'ettercap-graphical' has no installation candidate

**I tried The easiest way:** 

> root@kali:~/ettercap# mkdir build
> root@kali:~/ettercap# cd build
> root@kali:~/ettercap/build# cmake ../
> bash: cmake: command not found

Thanks

**Comment by koeppea** [comment]
You should first become familiar with the packaging system of you distribution.
In the first attempt the package name simply couldn't be found.
First you have to update the package list then search for the exact name then install.
apt-get update
apt-get search ettercap
sudo apt-get install <package name>
The second attempt primarily failed because you don't have cmake installed on your system. But for this way, much more dependencies have to be met. E.g. Git  repository cloned, various build utils installed and source code packages for quite a number of libraries. Without a certain level of basic Linux knowledge, I wouldn't recommend this path.
