### ISSUE TITLE
ettercap 0.8.2_1 shows every packets as UDP

### ISSUE THREAD

**Issue by Casanova402** [Ettercap/ettercap#833]
I tried on many machines, using kali, ubuntu and mac.
If I use ettercap to monitor the captures directly like this:
   `ettercap -Ti wlan0 -M arp /192.168.1.1// /192.168.1.10//`
then every packets will be shown as UDP packets, even though they are obviously TCP.
However, if I save the capture file, and reopen it using -r like this:
  `ettercap -Tr test.pcap`
then everything is right. Is there any solution to solve this? Because I want to use Filter, but in this case I can't capture it right.

**Comment by koeppea** [comment]
Standard question: Does this also happen when you use ettercap built from Github source?

**Comment by koeppea** [comment]
Using the your flavor of the ettercap command, I can reproduce the issue. However, this is somewhat intended. Since you didn't specified the ARP MITM attack with the "**remote**" parameter, only traffic inside the subnet is considered being _interessting_, so your TCP packets apparently went outside the local subnet.

If you specify `-M arp:remote` instead, the TCP packets are also shown.

The reason why ettercap shows the TCP packets when reading the PCAP file, is because there is no such distinction when ettercap is run in read-mode.

Can you confirm?

**Comment by koeppea** [comment]
Hope that explanation helped.
