### ISSUE TITLE
How can I use 'Ettercap' to hack the main gateway?

### ISSUE THREAD

**Issue by ayan-das1234** [Ettercap/ettercap#834]
I am on a local area network supporting upto 200+ customers connected to the main gateway router of the Company Providing the internet connection so now I want to hack the main Gateway Router in order to intercept all the connections plus the bandwidth and Internet!

**Comment by koeppea** [comment]
Please understand that this platform is meant do report issues or hand in enhancements for the software itself.
Search the web. There plenty tutorials out there. But be aware hacking isn't a no-brainer and vary from scenario to scenario.
But please don't hack w/o permission of the owner, otherwise it's illegal.
