### ISSUE TITLE
DoS filter?

### ISSUE THREAD

**Issue by Aideux** [Ettercap/ettercap#878]
Hey!

Since my plugins are all saved in .so format, I can't edit them (I wanted to create some more variations of DoS attacks for a school project.) Is there a way to write a filter that works the same way as the plugin does (sending tons of packets to an IP from an unused IP)? If so, can someone explain how this could be done? I'm very new Kali, and even newer to Ettercap, and any help would be much appreciated! Thank so much!

**Comment by koeppea** [comment]
plugins and filters are 2 different things.
Plugins are compiled at build time and cannot be modified like filters.
Filters are as their name suggests, reactive on the traffic that passes Ettercap. Hence proactively sending packets isn't the nature of filters.
If you're interesseted in writing your own pliugins, have a look at the source code into the dummy plugin. It shows the framework to program a plugin for Ettercap. But you'll need some experience with C programming of course.

Closing this issue since this is not a defect. Feel free to reopen.

**Comment by Aideux** [comment]
My issue is very much about the actual programming of the plugins as much as it is that I don’t really use C for networking purposes, so I would have no idea where to even begin to replicate the DoS plugin that already exists. Is there really no way to open/view the source code so that I can remake it? Thanks so much, I understand this may seem trivial, but you are being a wonderful help.

**Comment by Aideux** [comment]
P.S. by “source code” I mean the source to the “ec_dos_attack.so” file.

**Comment by gvanem** [comment]
@Aideux it's right there:
https://github.com/Ettercap/ettercap/blob/master/plug-ins/dos_attack/dos_attack.c

**Comment by Aideux** [comment]
Okay, wonderful. And one last question: how would I compile this into a runnable plugin? Thank you so much for your help!

**Comment by sgeto** [comment]
You won't get any help this way. You need to start educating yourself about compiling programs and then ask specific questions about particular problems/errors.

**Comment by Aideux** [comment]
Okay I'm having a particular issue during compilation using the command `gcc -shared -o attack_test.so -fPIC attack_test.c`. Specifically, when I run the command, I get the error `fatal error: ec.h: No such file or directory`. Any idea how to fix this issue?
