### ISSUE TITLE
Plugin compilation error

### ISSUE THREAD

**Issue by Aideux** [Ettercap/ettercap#879]
Okay I'm having a particular issue during compilation using the command `gcc -shared -o attack_test.so -fPIC attack_test.c.` Specifically, when I run the command, I get the `fatal error: ec.h: No such file or directory.` Any idea how to fix this issue? Thanks.

[EDIT] To give a little more issue background, I'm running this command from the desktop, where my C source code is located. Perhaps there's a specific place I need to put the source and run the command?

[EDIT 2] So I was able to get past the above error by running the command ` sudo apt-get install libssl-dev`, and then changing the line `#include <ec.h>` to `#include <openssl/ec.h>`, which seemed to negate the issue. Adding the `<openssl/` to the other includes did not work the same way. So now, instead of  `fatal error: ec.h: No such file or directory.`, it's  `fatal error: ec_plugins.h: No such file or directory.`. Any ideas for possible fixes? Thanks so much!

For reference, I'm building upon the the dos_attack.c source code from this link: https://github.com/Ettercap/ettercap/blob/master/plug-ins/dos_attack/dos_attack.c

**Comment by koeppea** [comment]
Read **README**. There you find all dependencies listed as a `apt-get` command. Maybe some packages are slightly different named depending on your distribution.
First you need to be able to build ettercap from source.
The easiest is trying to replicate the changes necessary to build your plugin together with ettercap, is to try to understand how it's done with the **dummy** plugin. You could even just try to integrate your code  into the dummy plugin source code file.

It's clear why your build command fails, since your compiler has no idea where to find the header file. But nobody here will try to understand your particular environment and not tell you how to get this fixed.
Take me above mentioned hint which is probably the most that you'll get.

**Comment by Aideux** [comment]
Thank you for your ongoing aid @koeppea. I really appreciate it.
