### ISSUE TITLE
10.0.2.2 i only have these adress when i scan the host and no other ip address

### ISSUE THREAD

**Issue by rezohs1234** [Ettercap/ettercap#929]
10.0.2.2 /10.0.2.3/10.0.2.4  i only have these adress when i scan the host with the eth0 interface and no other one like wtf im suppose to doing i thing 10.0.2.2 is  my router but the other wtf is that shit and why they dont detect my portable computer ta is 1 meter near

**Comment by koeppea** [comment]
> wtf is that shit

I can't tell because what and how you've composed this issue isn't useful at all.
Hence closing right away.
Feel free to open a new issue with some more facts and helpful information.
As always, try the latest code base from GitHub and compile in Debug mode which provides more debug information which may help to get down to your problem.
