### ISSUE TITLE
SEND L3 ERROR: 104 byte packet (86dd:3a) destined to ff02::1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)

### ISSUE THREAD

**Issue by KnightSec-Official** [Ettercap/ettercap#940]
I keep getting this error when i dns spoof. MAC OS - idk if reproducible... semms i got it when i run: 
ettercap -T -q -i en0 -M arp:remote -P dns_spoof //192.168.1.1// //192.168.1.11//
conf.dns changed the microsoft.com with service.facebook.com  A 127.0.0.1 (with tabs) all good and done there... but i still get this error every time... 
I dunno what have i done or havent done but if someone can help me fix this... it ll be much appreciated

**Comment by KnightSec-Official** [comment]
Listening on:
   en0 -> 78:CA:39:3F:B2:1E
	  192.168.1.10/255.255.255.0
	  2a02:2f0e:d116:7500:ecb3:403d:aad1:27bf/64
	  2a02:2f0e:d116:7500:877:9ae7:2b4:6432/64
	  fe80::872:ab56:e36d:404a/64

Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
24609 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

2 hosts added to the hosts list...
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help

Activating dns_spoof plugin...

SEND L3 ERROR: 104 byte packet (86dd:3a) destined to ff02::1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 104 byte packet (86dd:3a) destined to ff02::1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 104 byte packet (86dd:3a) destined to ff02::1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)

**Comment by KnightSec-Official** [comment]
and its not spoofing dns.... altrough i get errors sometimes when i use bettercap....but i could spoof other domains but gets me another errors...

libnet broken or my mac broken idk...

**Comment by sgeto** [comment]
I would probably try to disable IPv6 (in ettercap or system wide) and see
if that helps. See ettercap -h on how to do that.

If that doesn't help, then we would need more infos such as your ettercap
and libnet versions and possibly a debug/log file.

**Comment by KnightSec-Official** [comment]
i did it.... its worse
gave me so much errors and the tool wasnt scanning the net at all...i had to go to ipv6 back and try to spoof again....somehow i managed to spoof domains but the error still occurs.... but it doesnt affect me.... i can close this issue... tought it was from me... but i wanted to spoof facebook... which is protected by chrome, and i tought i couldn't cuz of that error but its fine....

**Comment by KnightSec-Official** [comment]
i had to forward my ip6 (ipv6) for the tool to work on other domains.... but now its cool.... thanks for help anyways! :D

**Comment by koeppea** [comment]
@KnightSec-Official Hi,
Do you have IPv6 Scanning active? From the command I'd doubt since it's the -6 switch.
The messages may come because ettercap received a all-nodes ICMPv6 multicast ping but the kernel doesn't know where and how to forward since it's not configured as a multicast router.

But back to your issue: I see you're MITM between 192.168.1.1 and 192.168.1.11 hoping that some DNS requests fly by to spoof. Correct?

Are you sure 192.168.1.11 has 192.168.1.1 configured as the resolver? (or vice versa - just assumed .1 is the DNS server and gateway).
Since you're residing in a Dual-stack network, the DNS requests may as well happen via IPv6. Therefore you need to take care of IPv6 based MITM also.
The following YouTube may be also interessting for you: https://www.youtube.com/watch?v=CalyetReLpA

**Comment by sgeto** [comment]
> @KnightSec-Official Hi,
> Do you have IPv6 Scanning active? From the command I'd doubt since it's the -6 switch.
> The messages may come because ettercap received a all-nodes ICMPv6 multicast ping but the kernel doesn't know where and how to forward since it's not configured as a multicast router.
> 
> But back to your issue: I see you're MITM between 192.168.1.1 and 192.168.1.11 hoping that some DNS requests fly by to spoof. Correct?
> 
> Are you sure 192.168.1.11 has 192.168.1.1 configured as the resolver? (or vice versa - just assumed .1 is the DNS server and gateway).
> Since you're residing in a Dual-stack network, the DNS requests may as well happen via IPv6. Therefore you need to take care of IPv6 based MITM also.
> The following YouTube may be also interessting for you: https://www.youtube.com/watch?v=CalyetReLpA

This is all very crucial information that many people aren't even aware of. How much of this is in ettercap's documentation (wiki or man page)?
IPv6 support is optional but most package maintainer enable it, which can cause problems like this one.
On Windows it's even worse. There we have a bug in libpcap that makes the IPv6 feature impossible to use. I'm not sure if this should be fixed upstream or here but it's definitely a helpful for people to know that we're aware of it and how to approach it.

We should do a write-up and/or video regarding ettercap and IPv6 to explain this feature to improve the docs and so that you don't have to repeat yourself.

**Comment by koeppea** [comment]
Check out the [YouTube Channel](https://www.youtube.com/channel/UCVYP1AeH9G1E1rtllwxLEQA) I've dedicated for our project.
However due to much more prominent Ettercap related videos, it's not easy to find them. At least if you search for Ettercap and IPv6 you directly find them.
The Cannel can be found if you Just search for Ettercap and filter for Channels.

What I could do in addition, to put the presentation or theory part as an own Wiki page so that the words are indexable. (I hope I still have the presentations).
