### ISSUE TITLE
Ettercap 8.3 will not uninstall

### ISSUE THREAD

**Issue by masonBackus** [Ettercap/ettercap#982]
New to Kali and Ettercap. After 8.2 Ettercap would not detect hosts, I had already uninstalled Ettercap 8.2 and then installed the GitHub 8.3 version before knowing it needs to be debugged and reinstalled. The 8.3 did install but still did not detect any hosts. So now I am also trying to uninstall 8.3 Ettercap version but it will not uninstall -- sudo apt-get purge or remove or uninstall or autoremove, nothing works.  "Virtual Packages like 'ettercap' can't be removed" according to apt-get remove --purge ettercap

**Comment by koeppea** [comment]
Since didn't install the self-compiled version of Ettercap with your package manager, it can not uninstall it.
You need to go to the build directory where you compiled Ettercap and type `sudo make uninstall`.

P.S.
If you want to get the scan issue further troubleshooted please reopen the other issue and provide the ettercap-0.8.3_debug.log file which is being created when you built Ettercap in Debug mode: `cmake -DCMAKE_BUILD_TYPE=Debug ..` instead of `cmake ..` during build procedure.
