### ISSUE TITLE
ettercap 0.8.3 cmake error

### ISSUE THREAD

**Issue by Delamhry** [Ettercap/ettercap#994]
Hello
i have a problem with ettercap.
when I write: cmake / root / ettercap
then show it to me:
Found Curses: /usr/lib/x86_64-linux-gnu/libncurses.so

    No GTK_BUILD_TYPE defined, default is GTK3
    CMake Error at cmake / Modules / FindGTK2.cmake: 382 (message):
    Could not find GTK3 include directory
    Call Stack (the most recent call first):
    cmake / Modules / EttercapLibCheck.cmake: 52 (find_package)
    CMakeLists.txt: 106

    Configuring Incomplete, Errors Occurred!
    See also "/root/ettercap/build/CMakeFiles/CMakeOutput.log".

**Comment by koeppea** [comment]
Well the error message is quite clear. It says that GTK3 development files could not be located. Probably because they’re not installed. Check the *README* file that contains the packages that are required at least for a Debian based distribution. Other distributions might have named them slightly different.

**Comment by nmhum** [comment]
Sorry、how to install GTK3？I can't install gtk3 properly.

**Comment by koeppea** [comment]
Please open a new issue if you have a problem. Then provide as post detail as possible that describes your problem, so that we have a chance to understand it.

Maybe you find already some useful information in [this Wiki article](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information).
